@AbapCatalog.sqlViewName: 'ZFIN_PROJ_V'
@AbapCatalog.compiler.compareFilter: true
@AbapCatalog.preserveKey: true
@AccessControl.authorizationCheck: #NOT_REQUIRED
@EndUserText.label: 'Project Master View'
@Metadata.ignorePropagatedAnnotations: true
@ObjectModel: { usageType.sizeCategory: #L,
                usageType.dataClass:  #ORGANIZATIONAL,
                usageType.serviceQuality: #A,
                supportedCapabilities: [#ANALYTICAL_DIMENSION, #CDS_MODELING_ASSOCIATION_TARGET, #SQL_DATA_SOURCE, #CDS_MODELING_DATA_SOURCE, #EXTRACTION_DATA_SOURCE],
                modelingPattern: #ANALYTICAL_DIMENSION
                }
@ClientHandling.algorithm: #SESSION_VARIABLE
@Analytics: {
      dataCategory: #FACT,
      dataExtraction: {
        enabled:true,
        delta.changeDataCapture: {
          mapping:
            [
              {
                table:'PRPS',
                role: #MAIN,
                viewElement: ['pspnr'],
                tableElement: ['pspnr']

              },
              {
                table:'PROJ',
                role: #LEFT_OUTER_TO_ONE_JOIN,
                viewElement: ['pspnr'],
                tableElement: ['pspnr']

              },
              {
                table:'PRTE',
                role: #LEFT_OUTER_TO_ONE_JOIN,
                viewElement: ['posnr'],
                tableElement: ['posnr']

              }
            ]
         }
      }
    }

define view ZFIN_I_PROJMASTER as select from prps
association[0..1] to proj on prps.mandt=proj.mandt
and prps.psphi=proj.pspnr
association[0..1] to prte on prps.mandt=PRTE.mandt 
and prps.psphi=PRTE.posnr
{
    key prps.pspnr,
    prps.psphi,
    prps.post1 as Post1,---same field exist in PROJ table.
    prps.objnr as Objnr,
    prps.poski as Poski,
    prps.ernam as Ernam,
    prps.erdat as Erdat,
    prps.aenam as Aenam,
    prps.aedat as Aedat,
    prps.vernr as Vernr,
    prps.verna as Verna,
    prps.astnr as Astnr,
    prps.astna as Astna,
    proj.pspid as Pspid,
    prps.posid as Posid,
    
    prps.pbukr as Pbukr,
    prps.pgsbr as Pgsbr,
    prps.pkokr as Pkokr,
    --PRPS.prctr as Prctr,
    prps.prart as Prart,
    prps.stufe as Stufe,
    prps.plakz as Plakz,
    prps.belkz as Belkz,
    prps.fakkz as Fakkz,
    prps.npfaz as Npfaz,
    --PRPS.zuord as Zuord,
    --PRPS.trmeq as Trmeq,
    prps.kvewe as Kvewe,
    prps.kappl as Kappl,
    prps.kalsm as Kalsm,
    prps.zschl as Zschl,
    --PRPS.abgsl as Abgsl,
    prps.akokr as Akokr,
    prps.akstl as Akstl,
    prps.fkokr as Fkokr,
    prps.fkstl as Fkstl,
    prps.fabkl as Fabkl,
    prps.pspri as Pspri,
    prps.equnr as Equnr,
    prps.tplnr as Tplnr,
    prps.pwpos as Pwpos,
    --PRPS.werks as Werks,
    --PRPS.txtsp as Txtsp,
    --PRPS.slwid as Slwid,
    --PRPS.usr00 as Usr00,
    --PRPS.usr01 as Usr01,
    --PRPS.usr02 as Usr02,
    --PRPS.usr03 as Usr03,
    --PRPS.usr04 as Usr04,
    --PRPS.use04 as Use04,
    --PRPS.usr05 as Usr05,
    --PRPS.use05 as Use05,
    --PRPS.usr06 as Usr06,
    --PRPS.use06 as Use06,
    --PRPS.usr07 as Usr07,
    --PRPS.use07 as Use07,
    --PRPS.usr08 as Usr08,
    --PRPS.usr09 as Usr09,
    --PRPS.usr10 as Usr10,
    --PRPS.usr11 as Usr11,
    --PRPS.kostl as Kostl,
    --PRPS.ktrg as Ktrg,
    --PRPS.berst as Berst,
    --PRPS.bertr as Bertr,
    --PRPS.berko as Berko,
    --PRPS.berbu as Berbu,
    prps.clasf as Clasf,
    --PRPS.spsnr as Spsnr,
    --PRPS.scope as Scope,
    --PRPS.xstat as Xstat,
    --PRPS.txjcd as Txjcd,
    --PRPS.zschm as Zschm,
    --PRPS.imprf as Imprf,
    prps.evgew as Evgew,
    prps.aennr as Aennr,
    prps.subpr as Subpr,
    --PRPS.postu as Postu,
    --PRPS.plint as Plint,
    --PRPS.loevm as Loevm,
    --PRPS.kzbws as Kzbws,
    prps.fplnr as Fplnr,
    prps.tadat as Tadat,
    prps.izwek as Izwek,
    prps.isize as Isize,
    prps.iumkz as Iumkz,
    prps.abukr as Abukr,
    prps.grpkz as Grpkz,
    prps.pgprf as Pgprf,
    prps.logsystem as Logsystem,
    prps.pspnr_logs as PspnrLogs,
    prps.stort as Stort,
    prps.func_area as FuncArea,
    prps.klvar as Klvar,
    prps.kalnr as Kalnr,
    prps.posid_edit as PosidEdit,
    prps.pspkz as Pspkz,
    prps.matnr as Matnr,
    prps.vlpsp as Vlpsp,
    prps.vlpkz as Vlpkz,
    prps.sort1 as Sort1,
    prps.sort2 as Sort2,
    prps.sort3 as Sort3,
    prps.vname as Vname,
    prps.recid as Recid,
    prps.etype as Etype,
    prps.otype as Otype,
    prps.jibcl as Jibcl,
    prps.jibsa as Jibsa,
    prps.cgpl_guid16 as CgplGuid16,
    prps.cgpl_logsys as CgplLogsys,
    prps.cgpl_objtype as CgplObjtype,
    prps.adpsp as Adpsp,
    prps.rfippnt as Rfippnt,
    prps.eew_prps_ps_dummy as EewPrpsPsDummy,
    prps.rfund as Rfund,
    prps.rgrant_nbr as RgrantNbr,
    prps.fund_fix_assign as FundFixAssign,
    prps.grant_fix_assigned as GrantFixAssigned,
    prps.func_area_fix_assigned as FuncAreaFixAssigned,
    prps.sponsoredprog as Sponsoredprog,
    prps.settlementelement as Settlementelement,
    prps.settlmtruleinherited as Settlmtruleinherited,
    prps.settlementobject as Settlementobject,
    prps.cpd_updat as CpdUpdat,
    prps.ferc_ind as FercInd,
    prps.prps_status as PrpsStatus,
    prps.posnr_prps as PosnrPrps,
    prps.vbeln_prps as VbelnPrps,
    --proj.post1 as Post1,
    --proj.objnr as Objnr,
    --proj.ernam as Ernam,
    --proj.erdat as Erdat,
    --proj.aenam as Aenam,
    --proj.aedat as Aedat,
    proj.kimsk as Kimsk,
    proj.autod as Autod,
    proj.stspd as Stspd,
    proj.stspr as Stspr,
    --proj.vernr as Vernr,
    --proj.verna as Verna,
    --proj.astnr as Astnr,
    --proj.astna as Astna,
    proj.vbukr as Vbukr,
    proj.vgsbr as Vgsbr,
    proj.vkokr as Vkokr,
    proj.prctr as Prctr,
    proj.pwhie as Pwhie,
    proj.zuord as Zuord,
    proj.trmeq as Trmeq,
    proj.plfaz as Plfaz,
    proj.plsez as Plsez,
    proj.werks as Werks,
    proj.kalid as Kalid,
    proj.vgplf as Vgplf,
    proj.ewplf as Ewplf,
    proj.zteht as Zteht,
    proj.nzanz as Nzanz,
    proj.plnaw as Plnaw,
    proj.vprof as Vprof,
    proj.profl as Profl,
    proj.bprof as Bprof,
    proj.txtsp as Txtsp,
    proj.kostl as Kostl,
    proj.ktrg as Ktrg,
    proj.aedte as Aedte,
    proj.aedtp as Aedtp,
    proj.berst as Berst,
    proj.bertr as Bertr,
    proj.berko as Berko,
    proj.berbu as Berbu,
    proj.spsnr as Spsnr,
    proj.besta as Besta,
    proj.scope as Scope,
    proj.xstat as Xstat,
    proj.txjcd as Txjcd,
    proj.zschm as Zschm,
    proj.scprf as Scprf,
    proj.imprf as Imprf,
    proj.fmprf as Fmprf,
    proj.abgsl as Abgsl,
    proj.postu as Postu,
    proj.pprof as Pprof,
    proj.plint as Plint,
    proj.loevm as Loevm,
    proj.inact as Inact,
    proj.kzbws as Kzbws,
    proj.smprf as Smprf,
    proj.flgvrg as Flgvrg,
    proj.grtop as Grtop,
    --proj.pgprf as Pgprf,
    --proj.stort as Stort,
    --proj.logsystem as Logsystem,
    proj.kzerb as Kzerb,
    proj.pargr as Pargr,
    --proj.func_area as FuncArea,
    proj.vkorg as Vkorg,
    proj.vtweg as Vtweg,
    proj.spart as Spart,
    proj.dppprof as Dppprof,
    proj.vpkstu as Vpkstu,
    proj.pspid_edit as PspidEdit,
    --proj.vname as Vname,
    --proj.recid as Recid,
    --proj.etype as Etype,
    --proj.otype as Otype,
    --proj.jibcl as Jibcl,
    --proj.jibsa as Jibsa,
    proj.eew_proj_ps_dummy as EewProjPsDummy,
    proj.schtyp as Schtyp,
    proj.sprog as Sprog,
    proj.eprog as Eprog,
    proj.order_proc_mode as OrderProcMode,
    proj.settlementtype as Settlementtype,
    proj.slwid as Slwid,
    proj.usr00 as Usr00,
    proj.usr01 as Usr01,
    proj.usr02 as Usr02,
    proj.usr03 as Usr03,
    proj.usr04 as Usr04,
    proj.use04 as Use04,
    proj.usr05 as Usr05,
    proj.use05 as Use05,
    proj.usr06 as Usr06,
    proj.use06 as Use06,
    proj.usr07 as Usr07,
    proj.use07 as Use07,
    proj.usr08 as Usr08,
    proj.usr09 as Usr09,
    proj.usr10 as Usr10,
    proj.usr11 as Usr11,
    --proj.cpd_updat as CpdUpdat,
    --proj.ferc_ind as FercInd,
    proj.avc_profile as AvcProfile,
    proj.avc_active as AvcActive,
    proj.cpcurr as Cpcurr,
    proj.proj_status as ProjStatus,
    
    
//    POSNR,
//PSPHI_PRTE,
//PSTRT,
//PENDE_PRTE,
//ESTRT,
//ISTRT
    prte.posnr as Posnr,
    --PRTE.psphi as Psphi,
    prte.pstrt as Pstrt,
    prte.estrt as Estrt,
    prte.istrt as Istrt,
    prte.pende as Pende,
    prte.eende as Eende,
    prte.iende as Iende
    
   }
where prps.mandt=$session.client
